# Arquivo: render.yaml

services:
  # Serviço para o Backend (API Flask)
  - type: web
    name: dashboard-os-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: FLASK_APP
        value: "main:app"
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: "sqlite:///../database/dev.db"
      - key: ADMIN_USER
        fromSecret: ADMIN_USER
      - key: ADMIN_PASS
        fromSecret: ADMIN_PASS
      - key: AUTH_TOKEN
        fromSecret: AUTH_TOKEN

  # Serviço para o Frontend (React)
  - type: static_site
    name: dashboard-os-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://dashboard-os-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
